### PR TITLE
Convnext

### PR DESCRIPTION
**Pull request by cBog**
# Integration of ConvNeXt model and support for training/pretraining configs

- implementation of `PipelineMixin` class for `ConvNextForImageClassification`
- extending the `run_image_classification_on_local_data.py` example code to run and validate training the model with 2 variants from the paper:
  - ImageNet-1K fine-tuning from ImageNet-22K pre-trained weights loaded from the original FB code [downloaded from this table](https://github.com/facebookresearch/ConvNeXt#imagenet-22k-trained-models)
  -  ImageNet-1K (pre/full) 300 epoch training code
- tested with the tiny model config size

Example training config files attached below, run with:

```
python3 run_image_classification_on_local_data.py ./<config>.json
```
Note: the full (pre)training configs are dependant on [this transformers bug fix](https://github.com/huggingface/transformers/pull/16699/files) in order to use stochastic depth as per the paper.

[ConvNeXt_configs.zip](https://github.com/huggingface/optimum-graphcore/files/8699717/ConvNeXt_configs.zip)

### CODE REVIEW

**Comment by jimypbr** [comment]
Please can add the model to the unit testing ala https://github.com/huggingface/optimum-graphcore/pull/81/files#diff-9e08e8c7769db7b58089fd7659d75ca96df40bb7b5d50299d3a30abd54da9ad6

**Comment by jimypbr** [comment]
Run `make style` to reformat with black.
Add `timm` as a dependency.

**Comment by dongkatgc** [comment]
Need update for this check failure! @jimypbr @C-Bogdiukiewicz

**Comment by jimypbr** [comment]
you'll need to rebase

**Comment by C-Bogdiukiewicz** [comment]
Sharing my list of planned changes:

- [ ] remove timm from setup.cfg and add to setup.py testing requirements (I put it in the wrong place)
- [ ] add a model card and ipu config at `Graphcore/convnext-tiny-ipu` for full 300 epoch training on a pod4 of tiny size in fp16 with cmd line to run in the readme (splitting out ipu-config and command line args from our mega configs attached above) 
- [ ] add convnext to the optimum-graphcore tests get it working/passing
- [ ] retest and confirm that the config/command in the ipu model card works
- [ ] revert FB weight loading code for the fine-tuning configs (we used this to test finetuning the tiny config from 22k pretrained which is not provided in the FB HF models)
- [ ] copy transforms needed for training over to the `run_image_classification.py` example now that imagenet-1k is available in HF datasets
- [ ] rebase

**Pull request closed without merging**
