### PR TITLE
Added image classification and language modelling from scratch notebooks

### PR DESCRIPTION
**Pull request by hja03**

### CODE REVIEW

**Comment by jimypbr** [comment]
Image classification notebooks:
1. Change the title to be "Optimum Graphcore" instead of "transformers"
2. Delete the section at the end with `pipelines`. We don't support those yet.

**Comment by jimypbr** [comment]
Also add to the examples/README.md

**Comment by hja03** [comment]
- Added notebooks to README
- Changed title
- Deleted pipeline section

**Comment by jimypbr** [comment]
LGTM. Thanks!

**Pull request merged**
