### PR TITLE
Fix doc build bugs

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

This PR fixes two bugs related to documentation generation:
- In the Docker image associated to the container building the doc, `hf-doc-builder` is installed from PyPI using `pip install .[quality]`. An install from source is needed to get [this fix](https://github.com/huggingface/doc-builder/pull/270).
- In the Docker image associated to the container building the doc, the repo is cloned but it points by default to the `main` branch. Thus, the doc generated for each PR is actually the doc of the `main` branch. This is fixed by checking out the commit associated to the PR when cloning the repo in the `Dockerfile`. See [here](https://github.com/huggingface/optimum-habana/pull/78) for more explanations.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by jimypbr** [comment]
Can you this merged?

**Comment by regisss** [comment]
Let me re-run the doc build test first, and if it passes I think it is good to be merged.

**Comment by regisss** [comment]
The test passed, let me know if I can merge @jimypbr

**Comment by jimypbr** [comment]
Go for it! 👍

**Pull request merged**
